# Generated by Django 5.1.6 on 2025-02-24 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('luz', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calefaccion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seguridad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aseo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
