# Generated by Django 5.1.6 on 2025-03-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_remove_usuario_username_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario Básico')], default='user', max_length=10),
        ),
    ]
